### ISSUE TITLE
Error in handleRoot example call

### ISSUE THREAD

**Issue by RiRomain** [dumpfheimer/OptoProxy#1]
Hello,

First, thanks for sharing this project, very useful :+1: 

Just noticed a tiny mistake when running the project for the first time. Calling the root IP returns the following:
"usage: /get?addr=0F43&len=2&conv=temp (len 0-4, conv: 0: raw, 1:temp, 2:temps, 3:stat, 4:count, 5:counts, 6:mode, 7:hours, 8:cop"
This appears to be wrong and it should be "read" not "get".

**Comment by dumpfheimer** [comment]
Thank you for pointing it out!
