### ISSUE TITLE
question about project

### ISSUE THREAD

**Issue by Jumbo125** [dumpfheimer/OptoProxy#2]
hello
i'm searching for a way, to get/send data via http request, to use the data in my php script. ESPHome is not so good for http request and Vitowifi is not so easy to create a new datapoint.
So i found your project.
It looks great.
Now i have some questions:

1. can i spend you tip?
2. do you use a libary from openv ????
3. do you use Vitowifi inside?
4. i only use arduino ide not platform io, but i will try it. You include some libarys in your script. #include <DPValue.hpp> #include <Datapoint.hpp>. where can i find this scripts????

Thank you a lot
I see, you use the vitowifi too. it will be included with platform.ino

**Comment by dumpfheimer** [comment]
Hi!

1. Thanks, but it's fine. I'm not in it for the money ;-)
2. &3. Yes, this project uses vitowifi for heater communication.
4. Platform.io should download everything needed as soon as you trigger the build. If you want to stick with Arduino ide for testing you could consider checking out the last commit before I migrated to platform io.

If you bump into any issues or find something I missed in the readme please let me know so I can make make it easier for the next person to get started

**Comment by Jumbo125** [comment]
Thank you for your answer
it is not my first work with visual studio platform io. so i get it really fast :-)
know i try to connect my wemos right.
i use thos tutorial:
https://github.com/Ixtalo/MyVitotronicLogger/blob/master/doc/Setup/WemosD1MiniVitoOptocoupler_bb.jpg

**Comment by dumpfheimer** [comment]
It looks like this on my Vitocal:
I have D0 to Ground for the receiving side (wich is on the green LED) and D1 to 3.3V on the sending side (with a resistor).

To be honest I'm not sure this sounds sane (has been a long time now and I have come a long way with micro electronics since then).
Everything is filled with hot glue, though, so it might be that I am missing something.

The JPG you linked looks sensible, although I do not know why D8 is grounded.
If you find a working configuration please let me know and I will put it in the readme

**Comment by Jumbo125** [comment]
on of the IR light, when i watch it via my smartphone camera. The other one not light.
i don't know if it is correct or how i can test it.

**Comment by dumpfheimer** [comment]
If you have a fairly young phone it might be that you have an IR filter which could prevent you from seeing anything.

Did you try both polarizations? What value resistor are you using?

**Comment by Jumbo125** [comment]
i'm not at home yet....
i only tried the first wiring from my picture
i use a 10k resistor for the SFH 309 and a 220ohm resistor for the sfh 4350
On of them light(flash/blink). Does both of them need to flash???
the sending IR should be flash. 
Should the recieving IR also flash?

**Comment by Jumbo125** [comment]
Did you defined D0 and D1 in the setting files?
If yes  i need to change it.

**Comment by Jumbo125** [comment]
Hy
i found in your settings 
#define OPTOLINK_OUT 0//D8
#define OPTOLINK_IN 2 //D9

What do you connect to d9

thank you!

**Comment by dumpfheimer** [comment]
those are commented out, so not really part of the code. I will remove them

**Comment by dumpfheimer** [comment]
As it is, the Software uses the default, main Serial interface to communicate with the heater. What device do you have and why do you think it is better to use other pins?

**Comment by Jumbo125** [comment]
Thank you for your answer.
I use a wemos d1 mini

I don't think it's better to use other pins. When i was read "#define OPTOLINK_IN 2 //D9" i thought, that i forgotten a wiring, becuase i didn't connect anything to D9

Now I know, that it wil be not use. 

What device do you have?
Do you know, if I need to enable the IR connection in the vitocal 200s?

I tried the selfmade plug yesterday. But i only get "timeout read" and after them only "link busy"

**Comment by dumpfheimer** [comment]
Ii have a WeMos D1R1 wich is like the D1 in matched to the form factor of an Arduino Uno.

Double check if you have a d1 mini or a d1 mini lite and change the platformio.ini to the right device. it might be using different gpio mapping.

**Comment by dumpfheimer** [comment]
You do not have to enable the OptoLink, it should be always on, I believe.

At this point you might want to know that booting the Vitocal 200S while having the OptoProxy connected prevents the Vitocal from booting up. I simply reset the ESP a few times when this happens which lets the Heater start normally. I do not know why this is happening and if this could be prevented easily (or if it might even be dangerous, wich I do not think it is)

**Comment by dumpfheimer** [comment]
Ok, so I have the following wiring:

Looking onto the heater I have the Optolink connector in front of me with the right LED glowing green. The green LED is the Sending Side

```
-----------
|  O   O  |
-----------
   ^   ^
 Off  Green

 TX     RX
10kΩ
3.3V    GND
```

The green side is connected to Ground + RX on the D1
The off side is connected to 3.3V + TX on the D1, separated by a 10kOhm resistor.

I do not know which LEDs / Phototransistors I was using, unfortunately. But it seems like you have done the research, as you have specified two models?
I can remember, though that the Phototransistor looked like a normal LED and the LED looked a bit odd. Make sure you have the right ones in the right positions and the right polarization.

**Comment by Jumbo125** [comment]
At this point you might want to know that booting the Vitocal 200S while having the OptoProxy connected prevents the Vitocal from booting up. I simply reset the ESP a few times when this happens which lets the Heater start normally. I do not know why this is happening and if this could be prevented easily (or if it might even be dangerous, wich I do not think it is)

okay thank you!
Do i understand it correct?
the heater doesn't start, when the optolink is pluged in?

**Comment by Jumbo125** [comment]
> The green side is connected to Ground + RX on the D1 The off side is connected to 3.3V + TX on the D1, separated by a 10kOhm resistor.
> 
> I do not know which LEDs / Phototransistors I was using, unfortunately. But it seems like you have done the research, as you have specified two models? I can remember, though that the Phototransistor looked like a normal LED and the LED looked a bit odd. Make sure you have the right ones in the right positions and the right polarization.

I will check it, when i'm at home.
Than you for your help

**Comment by dumpfheimer** [comment]
> Do i understand it correct?
> the heater doesn't start, when the optolink is pluged in?

Yes. The heater has this loading-bar when it starts (mine at least). As long as the OptoProxy ESP is connected, it will remain in this loading bar state. If you kill the OptoProxy it then starts normally. (Or you power it down first)

Another way that has came to my mind would be powering the ESP with power coming from the heater. That way the ESP would be powered down as long as the heater is powered down and the heater should be able to start up before the ESP is connected to the WIFI and starts talking to the heater. If that is not enough I would add an optional startup timeout.

When I have some time on my hands I will look into what the heater is sending and if it could be detected and prevented.

**Comment by dumpfheimer** [comment]
The sfh309 looks like a phototransistor, so yes, it belongs in the green LED. It should not flash. Are you positive you have the polarizations correct.

If the heater and the esp are up and everything is wired correctly you should be able to read datasets. No startup sequence or similar is needed.

**Comment by dumpfheimer** [comment]
Do you have a multimeter or even oscilloscope to test if the phototransistor is working?

**Comment by Jumbo125** [comment]
thank you for your help!!!
i'm so happy, for spending your time.

yes i have a multimeter.
i tested the resistor. yes, it shows 10kohm.
i tested the solder joint with the continuity mode. i hear always the signal pieeeeeeepppp.

when i put the red cable to one IR pin and the black cable(com) to the other pin i don't get a acustic signal with the connectivity mode. but this also don't work when i test it with the "correct/good" IR sensor.
how can i test the sfh309 with the multimeter?

**Comment by dumpfheimer** [comment]
You might be able to read a voltage over the sfh309. It should be apperent in, for example, sunlight. But it might also show something when you measure voltage while holding it to the green LED on the heater. Not sure if that's long enough for a multimeter to catch.

Did you say your LED blinks visibly on your phones camera? If not:
Do you have a normal, for example green, led lying around? If so you could try swapping the sending led to see if your pin on the ESP is still okay.

What power supply are you using? Might just be a power issue?

You could try running the esp while connected to a USB port on the computer (would be good if its a port capable of delivering more than 500mA) and read the logs (pio run -t monitor) there might be something useful there.

**Comment by dumpfheimer** [comment]
Any success?

**Comment by Jumbo125** [comment]
No.... :-( 
I tested it without my second resistor, because i the most tutorial is a 220ohm resistor too.
Nothing work. 
I will test more...

**Comment by dumpfheimer** [comment]
Wait a sec, are you connected to a PC ? Or are you using an external power source like a phone charger?

**Comment by Jumbo125** [comment]
> Did you try reading the logs?

Yes
I find out, it use baudrate 9600
I tested the serial monitor with arduino and Plattform io.
Both shows only:
``````````````

**Comment by Jumbo125** [comment]
I use it with pc and usb charger 2A. 5V

**Comment by dumpfheimer** [comment]
I think you should maybe stick to the USB charger. The PC might just mess with the serial connection when it tries to use the monitor.

I do not see any logs. Did something get lost?

**Comment by dumpfheimer** [comment]
Could you post the changes/configuration you made? Except wifi details of course.

**Comment by Jumbo125** [comment]
The log shows only:
/`````

**Comment by Jumbo125** [comment]
my settings are only the wifi settings:
#define WIFI_SSID "my_wifi_sid"
#define WIFI_PASSWORD "pw!"
#define WIFI_HOSTNAME "OptoProxy"

the conenction work. the wemos connect to my network wifi.

the link, which i use to test:
http://10.0.0.135/read?addr=0x0101&conv=temp

(i used other links too)

The answer:
time out and after i try it again, i get: LINK BUSY

i  use: 
#define OPTOLINK_CLASS OptolinkP300

should i use OptolinkKP??

**Comment by dumpfheimer** [comment]
Do you stop receiving the "," when you unplug your optolink connector?

**Comment by Jumbo125** [comment]
i got the same message

**Comment by Jumbo125** [comment]
i'm searching the problem and i found some problems. i found one problem. the ir was defect. 
I think the polarization isn't correct. can i post a picture and you show if it is correct?
![1692389087727-optolinkesp8266 (1)](https://github.com/dumpfheimer/OptoProxy/assets/61667987/66679a95-13dc-480b-8a2c-fab8f1a12d2b)

**Comment by dumpfheimer** [comment]
This setup seems unnecessarily complicated.
At least mine is working fine having a much simpler wiring.

Normally the longer leg should be connected to ground.

**Comment by Jumbo125** [comment]
hello
thank you. i will have a lok.
How doeas your sketch work?
vitowiffe makes it prssobe toste the datad url and check the data e.g. every 60 secondes

how does you script work?

normally the esp run a scipt in a defined intervall.
How you can make it possible, that i an send a request and get the current data= i tried this in ome other prjoects, too get data by request, but i dwn't know how i can setup this?

**Comment by dumpfheimer** [comment]
You can read data in two different ways:

Either the way you want to use it, by sending a http request. In that case the OptoProxy will read the data on demand, every time you call the http URL.

The other way is to define data points and let the OptoProxy read and send the values to a MQTT server.

I use both. MQTT for rapidly changing values such as temperature and http for other things like configurations.

**Comment by Jumbo125** [comment]
thats sound really good.
Is it difficult to config the esp, that it will do something, when i send a url request. 
I wrote some sketch, and i needed this function exactly.
I thought it's not possible for the esp, to do something if i send a http request with my browser

**Comment by dumpfheimer** [comment]
Not difficult at all!
Check out this: https://electropeak.com/learn/create-a-web-server-w-esp32/

**Comment by Jumbo125** [comment]
oh, thank you for the infos!

**Comment by Jumbo125** [comment]
works! Great!!!!!!!!!!!!!!!!
you are the best. thanks for your help!
can i spend you a beer or coffee?

**Comment by dumpfheimer** [comment]
Nice! What was the issue in the end?
Did you follow any other instructions (for example how to build the connector) that would be worth linking to in the readme of this project?

**Comment by Jumbo125** [comment]
I took a new IR and soldering some part new. The ground plug holds not so good. i fix this, so it holds good.
I need to use other IR Sensor because the IR sensor in the diagram is not avaible.
I draw my changes on the image and i will send it to you

**Comment by Jumbo125** [comment]
![wiring](https://github.com/dumpfheimer/OptoProxy/assets/61667987/42f251f7-82de-46fc-9bf3-29fae8e89568)

**Comment by dumpfheimer** [comment]
Don't apologize.

Do you have the Vitotronic WO1C?

**Comment by Jumbo125** [comment]
yes, i think so...
i have the vitocal 200S, 
but i can also use datapoints from VBC700_AW

**Comment by dumpfheimer** [comment]
If the heater is boiling water 0x0494 (stat) should be 1
If the compressor is on 0x0480 (stat) should be 1

Here is a complete list of the datapoints I use in a project:

outsideTemp temp 0x0101
ruecklaufTemp temp 0x0106
vorlaufTemp temp 0x0105
vorlaufSollTemp temp 0x1800
vorlaufKuehlenSollTemp temp 0x1803
wwTemp temp 0x010D
heizkennlinieNiveau temp 0x2006
heizkennlinieSteigung temp 0x2007
kuehlkennlinieNiveau temp 0x7110
kuehlkennlinieSteigung temp 0x7111
minVorlaufKuehlen temp 0x7103
raumSollTemp temp 0x2000
raumSollRedTemp temp 0x2001
raumIstTemp temp 0x0116
betriebsart mode 0xb000
ventHeizenWW stat 0x0494
ventHeizenKuehlen stat 0x0494
hkPumpOn stat 0x048D
ventilatorOn stat 0x04a6
compressorOn stat 0x0480
isCooling stat 0x04a6
temperatureRegulationMode mode 0x2005
wwBereitung mode 0xB020
wwTempSoll1 temp 0x6000
wwTempSoll2 temp 0x600C
anzEinschaltungenSec count 0x600C
kwhHeizen count 0x1660
kwhWW count 0x1670
copGes cop 0x1680
copH cop 0x1681
copWW cop 0x1682
copC cop 0x1683
primSourcePercent counts 0xB420
secPumpPercent counts 0xB421
wwPumpPercent counts 0xB422
verdichterPercent counts 0xB423
ecvPercent counts 0xB424

**Comment by Jumbo125** [comment]
thanl you, shows betriebsart mode 0xb000 if the boiler heat at this moment?
do you know what Red Temp mean?

**Comment by dumpfheimer** [comment]
Betriebsart ist the "overall mode" in which the therme es. For example "warm water only" or "heat/cool/we" can look up the values if you like

**Comment by dumpfheimer** [comment]
Do you mean raumSollRedTenp?
That's the Raum Soll Reduziert Temperatur, you have two setpoints. One "default" and one "Reduziert" (=reduced) which can be used for vacation or Nachtabsenkung (=reduced temperature during the night)

**Comment by Jumbo125** [comment]
yes, i do.

thank you, i didn't know whats red.temp mean, so i know: Thats a second value for special times liike vacation or nachtabsenkung. i believe, i don't use a nachtabsenkung

**Comment by dumpfheimer** [comment]
I don't either. Especially when you can automatically change the normal Raum Soll temp as you desire..

**Comment by Jumbo125** [comment]
Thank you a lot
i will try to find my datapoint. Your codes not work for me :-( but i don't give up. 
My device id shows 204d... thats mean WO1 but this datapoint get also not correct values... 
At the moment i use the datapoints from this list.... i don't know why the VBC700 datapoints work for me.....
[DP_VBC700_AW.csv](https://github.com/dumpfheimer/OptoProxy/files/12446921/DP_VBC700_AW.csv)

I'm a little bit sad, because i neve got a string back, like "heat/cool/we" or something else.... only numbers like 1-3....
i treid to use state, mode, stat, raw... nothing helps

**Comment by Jumbo125** [comment]
i found a list :-) 
[Vitocal 200-S Datenblatt.pdf](https://github.com/dumpfheimer/OptoProxy/files/12446966/Vitocal.200-S.Datenblatt.pdf)

**Comment by Jumbo125** [comment]
@dumpfheimer 
sorry to bother you again
i treid to write my first datapoint

is it possible that the link in you description not work?
![image](https://github.com/dumpfheimer/OptoProxy/assets/61667987/dd57f143-3f05-46c5-838d-e894b240dafb)
is it correct to change read with write?

**Comment by dumpfheimer** [comment]
Yes, sorry!

It should be http://<IP_OF_ESP8266>/write?addr=0x2000&conv=temp&val=21

**Comment by dumpfheimer** [comment]
> I'm a little bit sad, because i neve got a string back, like "heat/cool/we" or something else.... only numbers like 1-3....
i treid to use state, mode, stat, raw... nothing helps
Yeah, you will only ever get binary / numeric data back. It greatly depends on the heater model and data point what that values means.

**Comment by dumpfheimer** [comment]
> by the way, is it possible to add multiple get parameter with one request or does the webserver on the esp only work with one parameter each request?

No, its always one value.

Having multiple values would increase complexity in error handling and is frankly not really worth the effort. Multiple HTTP requests in series work fine and pretty much as fast as the heater can handle the requests, so there is not really a huge benefit to it

**Comment by Jumbo125** [comment]
thank you a lot!
is it okay, if i ask you something, if i need help? or is it enough for you free time and you can't spend more time?

**Comment by dumpfheimer** [comment]
Sure, keep asking!
I am glad to help, it just might take some time for me to get back to you (and if I don't for a few days don't hesitate to remind me, I do lose track of stuff "from time to time")

Did you try converting with *conv=mode* or *conv=mode*?

**Comment by Jumbo125** [comment]
oh sorry wrong picture. 
i mean a other value.
here is the picture:
![image](https://github.com/dumpfheimer/OptoProxy/assets/61667987/8110f0b1-1836-4af4-b5f2-30d544b2914f)
it shows the working state in percentage.
so i used count.
i tried a lot of ideas and i fthink it works now. i user it with counts 
"s" on the end of count

**Comment by Jumbo125** [comment]
do you use the same datapoints like vitowifi project? can i use all the same datpoints from his github tutorial?

**Comment by dumpfheimer** [comment]
0xB423 should be counts, right.
It means count+state. For compressor state that means you will know how often the compressor had started and if it is running right now by reading that one value. Not sure if both values are passed in the http response right now.

> do you use the same datapoints like vitowifi project?

The data points depend on your heater rather than VitoWiFi/Optolink/whatever you will need to find a document for your specific heater that lists the data points. Many of them, that are used for configuration, are in the manual or service manual of the heater. But there are many other ones too that Viessmann seems to want to keep out of public.

I could only guess if the energy is electricity in or heat out. But I can remember them being quite inaccurate, it's more like a guess.

**Comment by Jumbo125** [comment]
i see. thank you a lot!

**Comment by Jumbo125** [comment]
hy @dumpfheimer 
do you have problems with writing datas?

i try to write warmwasser hysterese 
http://10.0.0.135/write?addr=0x6007&conv=temp&val=4

or heating with electro
http://10.0.0.135/write?addr=0x6015&conv=mode&val=0

i only get always "INVALID_ADDRESS"

**Comment by dumpfheimer** [comment]
Hi!

The data points that can be written are limited in the code:
https://github.com/dumpfheimer/OptoProxy/blob/master/software/src/optolink.cpp#L123-L154

This is done to prevent writing to wrong/unknown/unintended data points. Feel free to add extra data points.

**Comment by Jumbo125** [comment]
oh, really nice idea!!! 
i wil pass it for me. hope my datapoints are read/writeable .
Thank yous
Sorry for the bothering

**Comment by dumpfheimer** [comment]
As long as you do not define MQTT_HOST mqtt is not enabled. Hope you were successful with your project
