### ISSUE TITLE
Question about the hardware you are using

### ISSUE THREAD

**Issue by pgmeiner** [dumpfheimer/OptoProxy#3]
I have a simple question about the hardware you are using.
Since the optolink adapter has a USB output we would need a USB adapter to use it with an ESP8266 ESP-01S, right?
So the optolink is directly connected via USB to the ESP8266 and cannot supply the ESP with power. So where is the power supply coming from? Is it connected via a Vin pin on the ESP8266? 
If yes can you recommend a specific ESP module and a power supply unit that could be used for your proxy solution? Sorry, I'm not so experienced in the microcontroller world.

**Comment by dumpfheimer** [comment]
There is no USB involved.
Not sure what you mean with "Optolink adapter", though.

The Optolink part is just a 3D printed part containing a infrared LED and infrared Phototransistor which closes the loop for a serial connection.

**Comment by pgmeiner** [comment]
For example the optolink adapter from vitoconnect has an USB connector:

![image](https://github.com/dumpfheimer/OptoProxy/assets/61839563/148259a3-eebe-474b-9189-2a2377448614)

**Comment by dumpfheimer** [comment]
Ah okay, now I know what you mean.

This project would replace that part completely. The intended setup would be:

You build that plastic piece with the "V" yourself. It contains said LED and phototransistor. You connect it to your ESP, configure and flash this project to your ESP and the rest is done via WLAN.

So, sou would need:
1x ESP
1x Infrared LED
1x Infrared Phototransistor
1x cable to connect them together (4 wires)
1x 1000Oh resistor
1x Power supply with USB cable to power the ESP

You do not need that USB adapter.

**Comment by pgmeiner** [comment]
Ok, thanks for your answer. Unfortunately, I do not have the equipment and skills to make such an adapter by myself.

**Comment by dumpfheimer** [comment]
Maybe vitoconnect from Viessmann is something for you, if you haven't already stumbled upon it?

**Comment by pgmeiner** [comment]
I already considered that, but when I understand it correctly with Vitoconnect I'm not able to send the data to my own webserver.

**Comment by dumpfheimer** [comment]
Probably not without jumping through hoops, no..

**Comment by dumpfheimer** [comment]
Feel free to reopen this issue
